### ISSUE TITLE
Demo User

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang#3]
## 💰 Feature
User can sign in without having to sign up

## ✅ Tasks

- [x] Create demo user account with matches to demo users
- [x] Create login UI
- [x] Set username and password state in login form to values of demo user
- [x] Disable username and password inputs
- [x] Create Login POST express route at '/api/auth/sign-in'
- [x] Compare the username and password to the username and password in the database
- [x] Return the token to the clientside
- [x] Create client side POST fetch to '/api/auth/sign-in'
- [x] Store userId with token in localStorage
- [x] Forward to /pairing/select
