### ISSUE TITLE
Style Updates

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang#4]
## 💰 Feature
User can see name/time for each message sent

## ✅ Tasks

- [x] Add name of partner in each message received
- [x] Create time for message in PostgreSQL database
- [x] Add time to the UI of each message
