### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang#5]
## 💰 Feature
Make design responsive

## ✅ Tasks

- [x] Create media queries for each screen size (mobile, tablet, desktop)
- [x] Adjust font and button size for larger screens
- [x] Add max width for desktop screen size
